name: otraku
description: An unofficial AniList app.

publish_to: 'none'

version: 1.5.3+77

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State management.
  flutter_riverpod: ^2.5.1

  # Routing.
  go_router: ^14.3.0

  # Data fetching.
  http: ^1.2.2

  # Settings storage.
  hive: ^2.2.3

  # Access to device storage. Used for [hive] setup.
  path_provider: ^2.1.4

  # Secure storage for the access tokens.
  flutter_secure_storage: ^9.2.2

  # Markdown to HTML parsing.
  markdown: ^7.2.2

  # Used for configuring [cached_network_image], which already imports it.
  flutter_cache_manager: ^3.4.1

  # Image caching.
  cached_network_image: ^3.4.1

  # Opening links in the browser.
  url_launcher: ^6.3.1

  # Access to platform theme and easy theme interpolation.
  dynamic_color: ^1.7.0

  # Background tasks for notification fetching.
  workmanager: ^0.5.2

  # Sending device notifications.
  flutter_local_notifications: ^17.2.3

  # Translating html into flutter widgets.
  flutter_widget_from_html_core: ^0.15.2

  # An addition to the material icons.
  ionicons: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_icons:
  ios: true
  android: true
  image_path: "assets/icons/ios.png"
  adaptive_icon_background: "#0D161E"
  adaptive_icon_foreground: "assets/icons/android.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/about.png

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
        - asset: assets/fonts/Rubik-Italic.ttf
          style: italic
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik-MediumItalic.ttf
          weight: 500
          style: italic
