name: otraku
description: An unofficial AniList app.

publish_to: 'none'

version: 1.10.1+89

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State management.
  flutter_riverpod: ^3.0.3

  # Routing.
  go_router: ^17.0.0

  # Data fetching.
  http: ^1.6.0

  # Lightweight storage.
  hive: ^2.2.3

  # Access to device storage. Used for [hive] setup.
  path_provider: ^2.1.5

  # Secure storage for the access tokens.
  flutter_secure_storage: ^9.2.4

  # Markdown to HTML parsing.
  markdown: ^7.3.0

  # Used for configuring [cached_network_image].
  flutter_cache_manager: ^3.4.1

  # Image caching.
  cached_network_image: ^3.4.1

  # Opening links in the browser.
  url_launcher: ^6.3.2

  # Access to platform theme and easy theme interpolation.
  dynamic_color: ^1.8.1

  # Background tasks for notification fetching.
  workmanager: ^0.9.0+3

  # Sending device notifications.
  flutter_local_notifications: ^19.5.0

  # Parsing html into flutter widgets.
  flutter_widget_from_html_core: ^0.17.0

  # Transformation calculations.
  vector_math: ^2.2.0

  # An addition to the material icons.
  ionicons: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter_icons:
  ios: true
  android: true
  image_path: "assets/icons/ios.png"
  adaptive_icon_background: "#0D161E"
  adaptive_icon_foreground: "assets/icons/android.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/about.png

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-VariableFont_wght.ttf
        - asset: assets/fonts/Rubik-Italic-VariableFont_wght.ttf
          style: italic
